name: CD Pipeline
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r assets/dev-requirements.txt
    - name: Linter
      run: |
       black --check . 
    - name: Run Tests
      run: |
        pytest  tests/db_test.py --cov
